set(MSYS_TARGET_ARCHITECTURE x86)
set(MSYS_CRT_LINKAGE dynamic)
set(MSYS_LIBRARY_LINKAGE dynamic)
set(MSYS_ENV_PASSTHROUGH PATH)

set(VCPKG_CMAKE_SYSTEM_NAME MinGW)
set(VCPKG_POLICY_DLLS_WITHOUT_LIBS enabled)
