set(MSYSTEM MINGW64)

set(MSYS_TARGET_ARCHITECTURE x64)
set(MSYS_CRT_LINKAGE dynamic)
set(MSYS_LIBRARY_LINKAGE dynamic)
# set(MSYS_ENV_PASSTHROUGH PATH)
set(MSYS_PATH_TYPE "inherit")

set(MSYS_CMAKE_SYSTEM_NAME MinGW)
set(MSYS_POLICY_DLLS_WITHOUT_LIBS enabled)
