if(TRACE_MODE)
    message("Enter: ${CMAKE_CURRENT_LIST_FILE}")
endif()

if(MSYSTEM STREQUAL "MINGW64"
    OR MSYSTEM STREQUAL "MINGW32"
    OR MSYSTEM STREQUAL "UCRT64")
    include(Platform/MSYSTEM-GNU-CXX)
elseif(MSYSTEM STREQUAL "CLANG64"
    OR MSYSTEM STREQUAL "CLANG32"
    OR MSYSTEM STREQUAL "CLANGARM64")
    include(Platform/MSYSTEM-CLANG-CXX)
elseif(MSYSTEM STREQUAL "MSYS2")
    include(Platform/MSYS-GNU-CXX)
endif()

if(TRACE_MODE)
    message("Exit: ${CMAKE_CURRENT_LIST_FILE}")
endif()
