set(MINGW64_OBJC_COMPILER "C:/msys64/mingw64/bin/gcc.exe")
set(MINGW64_OBJC_COMPILER_ARG1 "")
set(MINGW64_OBJC_COMPILER_ID "GNU")
set(MINGW64_OBJC_COMPILER_VERSION "13.1.0")
set(MINGW64_OBJC_COMPILER_VERSION_INTERNAL "")
set(MINGW64_OBJC_COMPILER_WRAPPER "")
set(MINGW64_OBJC_STANDARD_COMPUTED_DEFAULT "90")
set(MINGW64_OBJC_EXTENSIONS_COMPUTED_DEFAULT "ON")
set(MINGW64_OBJC_COMPILE_FEATURES "")
set(MINGW64_OBJC90_COMPILE_FEATURES "")
set(MINGW64_OBJC99_COMPILE_FEATURES "")
set(MINGW64_OBJC11_COMPILE_FEATURES "")
set(MINGW64_OBJC17_COMPILE_FEATURES "")
set(MINGW64_OBJC23_COMPILE_FEATURES "")

set(MINGW64_OBJC_PLATFORM_ID "MinGW")
set(MINGW64_OBJC_SIMULATE_ID "")
set(MINGW64_OBJC_COMPILER_FRONTEND_VARIANT "GNU")
set(MINGW64_OBJC_SIMULATE_VERSION "")



set(MINGW64_OBJC_COMPILER_AR "C:/msys64/mingw64/bin/gcc-ar.exe")
set(MINGW64_OBJC_COMPILER_RANLIB "C:/msys64/mingw64/bin/gcc-ranlib.exe")


set(MINGW64_COMPILER_IS_GNUOBJC 1)
set(MINGW64_OBJC_COMPILER_ENV_VAR "OBJC")


set(MINGW64_OBJC_SOURCE_FILE_EXTENSIONS m)
set(MINGW64_OBJC_IGNORE_EXTENSIONS h;H;o;O)

foreach(lang C CXX OBJCXX)
    foreach(extension IN LISTS MINGW64_OBJC_SOURCE_FILE_EXTENSIONS)
        if (MINGW64_${lang}_COMPILER_ID_RUN)
            list(REMOVE_ITEM MINGW64_${lang}_SOURCE_FILE_EXTENSIONS ${extension})
        endif()
    endforeach()
endforeach()

# Save compiler ABI information.
set(MINGW64_OBJC_SIZEOF_DATA_PTR "8")
set(MINGW64_OBJC_COMPILER_ABI "")
set(MINGW64_OBJC_BYTE_ORDER "LITTLE_ENDIAN")
set(MINGW64_OBJC_LIBRARY_ARCHITECTURE "")

if(MINGW64_OBJC_SIZEOF_DATA_PTR)
    set(MINGW64_SIZEOF_VOID_P "${MINGW64_OBJC_SIZEOF_DATA_PTR}")
endif()

if(MINGW64_OBJC_COMPILER_ABI)
    set(MINGW64_INTERNAL_PLATFORM_ABI "${MINGW64_OBJC_COMPILER_ABI}")
endif()

if(MINGW64_OBJC_LIBRARY_ARCHITECTURE)
    set(MINGW64_LIBRARY_ARCHITECTURE "")
endif()





set(MINGW64_OBJC_IMPLICIT_INCLUDE_DIRECTORIES "C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/13.1.0/include;C:/msys64/mingw64/include;C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/13.1.0/include-fixed")
set(MINGW64_OBJC_IMPLICIT_LINK_LIBRARIES "mingw32;gcc;moldname;mingwex;kernel32;pthread;advapi32;shell32;user32;kernel32;mingw32;gcc;moldname;mingwex;kernel32")
set(MINGW64_OBJC_IMPLICIT_LINK_DIRECTORIES "C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/13.1.0;C:/msys64/mingw64/lib/gcc;C:/msys64/mingw64/x86_64-w64-mingw32/lib;C:/msys64/mingw64/lib")
set(MINGW64_OBJC_IMPLICIT_LINK_FRAMEWORK_DIRECTORIES "")
